import React, { useState, useMemo } from 'react';
import { Header } from './components/Header';
import { ControlPanel, Presets, HOMEWORK_PRESETS } from './components/ControlPanel';
import { BodeChart } from './components/BodeChart';
import { PoleZeroMap } from './components/PoleZeroMap';
import { HomeworkBreakdown } from './components/HomeworkBreakdown';
import { analyzeTransferFunction, BodeAnalysisResult } from './utils/bodeEngine';
import { parseTFString } from './utils/stringParser';

export const App: React.FC = () => {
  const [inputMode, setInputMode] = useState<'poly' | 'expr'>('poly');
  const [numStr, setNumStr] = useState<string>('25');
  const [denStr, setDenStr] = useState<string>('1 4 25');
  const [exprStr, setExprStr] = useState<string>('25 / (s^2 + 4*s + 25)');

  const [omegaMinPower, setOmegaMinPower] = useState<number>(-2);
  const [omegaMaxPower, setOmegaMaxPower] = useState<number>(4);

  const [showAsymptotic, setShowAsymptotic] = useState<boolean>(true);
  const [showMargins, setShowMargins] = useState<boolean>(true);
  const [showGrid, setShowGrid] = useState<boolean>(true);
  const [showPoleZeroMap, setShowPoleZeroMap] = useState<boolean>(true);

  const [reportMode, setReportMode] = useState<boolean>(false);

  // Compute Bode Analysis Result reactively
  const analysisResult = useMemo<BodeAnalysisResult>(() => {
    let numCoeffs: number[] = [1];
    let denCoeffs: number[] = [1, 1];

    if (inputMode === 'poly') {
      const parseNums = (str: string) =>
        str
          .trim()
          .split(/[\s,]+/)
          .map(v => parseFloat(v))
          .filter(v => !isNaN(v));

      const parsedNum = parseNums(numStr);
      const parsedDen = parseNums(denStr);

      if (parsedNum.length > 0) numCoeffs = parsedNum;
      if (parsedDen.length > 0) denCoeffs = parsedDen;
    } else {
      const parsed = parseTFString(exprStr);
      numCoeffs = parsed.numCoeffs;
      denCoeffs = parsed.denCoeffs;
    }

    return analyzeTransferFunction(numCoeffs, denCoeffs, omegaMinPower, omegaMaxPower, 400);
  }, [inputMode, numStr, denStr, exprStr, omegaMinPower, omegaMaxPower]);

  const handleSelectPreset = (preset: Presets) => {
    setNumStr(preset.num.join(' '));
    setDenStr(preset.den.join(' '));
    setExprStr(preset.expr);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div style={{ minHeight: '100dvh', backgroundColor: 'var(--color-surface-muted)' }}>
      <Header
        reportMode={reportMode}
        onToggleReportMode={() => setReportMode(!reportMode)}
        onPrint={handlePrint}
      />

      <main className="container" style={{ padding: '1.5rem 1rem' }}>
        {/* Printable Header for Homework Submissions */}
        <div className="print-only" style={{ display: 'none', marginBottom: '1.5rem', borderBottom: '2px solid #000', paddingBottom: '0.75rem' }}>
          <h1 style={{ fontSize: '1.8rem', color: '#000', margin: 0 }}>Bode Plot Homework Analysis Report</h1>
          <p style={{ fontSize: '0.9rem', color: '#444', margin: '0.25rem 0 0 0' }}>
            Generated by BodeNgeplot Engineering Studio — Date: {new Date().toLocaleDateString()}
          </p>
        </div>

        {/* Controls (Hidden during print) */}
        {!reportMode && (
          <ControlPanel
            numStr={numStr}
            denStr={denStr}
            exprStr={exprStr}
            inputMode={inputMode}
            onNumChange={setNumStr}
            onDenChange={setDenStr}
            onExprChange={setExprStr}
            onInputModeChange={setInputMode}
            onSelectPreset={handleSelectPreset}
            omegaMinPower={omegaMinPower}
            omegaMaxPower={omegaMaxPower}
            onOmegaMinChange={setOmegaMinPower}
            onOmegaMaxChange={setOmegaMaxPower}
            showAsymptotic={showAsymptotic}
            showMargins={showMargins}
            showGrid={showGrid}
            showPoleZeroMap={showPoleZeroMap}
            onToggleAsymptotic={() => setShowAsymptotic(!showAsymptotic)}
            onToggleMargins={() => setShowMargins(!showMargins)}
            onToggleGrid={() => setShowGrid(!showGrid)}
            onTogglePoleZeroMap={() => setShowPoleZeroMap(!showPoleZeroMap)}
          />
        )}

        {/* Main Grid Visualizations */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: showPoleZeroMap ? '1fr 340px' : '1fr',
          gap: '1.25rem',
          marginTop: reportMode ? '0' : '1.25rem'
        }}>
          <div>
            <BodeChart
              analysis={analysisResult}
              showAsymptotic={showAsymptotic}
              showMargins={showMargins}
              showGrid={showGrid}
              omegaMinPower={omegaMinPower}
              omegaMaxPower={omegaMaxPower}
            />
          </div>

          {showPoleZeroMap && (
            <div>
              <PoleZeroMap poles={analysisResult.poles} zeros={analysisResult.zeros} />
            </div>
          )}
        </div>

        {/* Step-by-Step Breakdown */}
        <HomeworkBreakdown analysis={analysisResult} />
      </main>
    </div>
  );
};
export default App;
