import React, { useState, useMemo } from 'react';
import { Header } from './components/Header';
import { ControlPanel } from './components/ControlPanel';
import { BodeChart } from './components/BodeChart';
import { PoleZeroMap } from './components/PoleZeroMap';
import { HomeworkBreakdown } from './components/HomeworkBreakdown';
import { TutorialModal } from './components/TutorialModal';
import { analyzeTransferFunction, BodeAnalysisResult } from './utils/bodeEngine';
import { parseTFString } from './utils/stringParser';
import { parseZPK, zpkToPolynomials } from './utils/zpkParser';
import { parseLocalNumberList } from './utils/formatUtils';

export const App: React.FC = () => {
  const [inputMode, setInputMode] = useState<'poly' | 'expr' | 'zpk'>('expr');
  const [numStr, setNumStr] = useState<string>('1 1');
  const [denStr, setDenStr] = useState<string>('1 100');
  const [exprStr, setExprStr] = useState<string>('(s + 1) / (s + 100)');
  const [zpkGainStr, setZpkGainStr] = useState<string>('1');
  const [zpkZerosStr, setZpkZerosStr] = useState<string>('-1');
  const [zpkPolesStr, setZpkPolesStr] = useState<string>('-100');

  const [exprError, setExprError] = useState<string | null>(null);
  const [lastValidCoeffs, setLastValidCoeffs] = useState<{ num: number[]; den: number[] }>({
    num: [1, 1],
    den: [1, 100]
  });

  const [omegaMinPower, setOmegaMinPower] = useState<number>(-2);
  const [omegaMaxPower, setOmegaMaxPower] = useState<number>(4);

  const [showAsymptotic, setShowAsymptotic] = useState<boolean>(true);
  const [showFactorBreakdown, setShowFactorBreakdown] = useState<boolean>(true);
  const [selectedFactorId, setSelectedFactorId] = useState<string | null>(null);
  const [hoveredFactorId, setHoveredFactorId] = useState<string | null>(null);
  const [showMargins, setShowMargins] = useState<boolean>(true);
  const [showGrid, setShowGrid] = useState<boolean>(true);
  const [showPoleZeroMap, setShowPoleZeroMap] = useState<boolean>(true);
  const [isTutorialOpen, setIsTutorialOpen] = useState<boolean>(false);

  const handleSelectFactor = (id: string | null) => {
    setSelectedFactorId(prev => (prev === id || id === null ? null : id));
  };

  const activeFactorId = hoveredFactorId !== null ? hoveredFactorId : selectedFactorId;

  // Compute Bode Analysis Result reactively
  const analysisResult = useMemo<BodeAnalysisResult>(() => {
    let numCoeffs = lastValidCoeffs.num;
    let denCoeffs = lastValidCoeffs.den;

    if (inputMode === 'poly') {
      const parsedNum = parseLocalNumberList(numStr);
      const parsedDen = parseLocalNumberList(denStr);

      if (parsedNum.length > 0 && parsedDen.length > 0) {
        numCoeffs = parsedNum;
        denCoeffs = parsedDen;
        setExprError(null);
        if (JSON.stringify(lastValidCoeffs) !== JSON.stringify({ num: parsedNum, den: parsedDen })) {
          setLastValidCoeffs({ num: parsedNum, den: parsedDen });
        }
      }
    } else if (inputMode === 'expr') {
      const parsed = parseTFString(exprStr);
      if (parsed.error || parsed.numCoeffs.length === 0 || parsed.denCoeffs.length === 0) {
        setExprError(parsed.error || "Incomplete expression syntax");
      } else {
        setExprError(null);
        numCoeffs = parsed.numCoeffs;
        denCoeffs = parsed.denCoeffs;
        if (JSON.stringify(lastValidCoeffs) !== JSON.stringify({ num: parsed.numCoeffs, den: parsed.denCoeffs })) {
          setLastValidCoeffs({ num: parsed.numCoeffs, den: parsed.denCoeffs });
        }
      }
    } else if (inputMode === 'zpk') {
      const parsedZpk = parseZPK(zpkGainStr, zpkZerosStr, zpkPolesStr);
      const polys = zpkToPolynomials(parsedZpk.gain, parsedZpk.zeros, parsedZpk.poles);
      if (polys.numCoeffs.length > 0 && polys.denCoeffs.length > 0) {
        numCoeffs = polys.numCoeffs;
        denCoeffs = polys.denCoeffs;
        setExprError(null);
        if (JSON.stringify(lastValidCoeffs) !== JSON.stringify({ num: polys.numCoeffs, den: polys.denCoeffs })) {
          setLastValidCoeffs({ num: polys.numCoeffs, den: polys.denCoeffs });
        }
      }
    }

    return analyzeTransferFunction(numCoeffs, denCoeffs, omegaMinPower, omegaMaxPower, 400);
  }, [inputMode, numStr, denStr, exprStr, zpkGainStr, zpkZerosStr, zpkPolesStr, omegaMinPower, omegaMaxPower, lastValidCoeffs]);

  return (
    <div style={{ minHeight: '100dvh', backgroundColor: 'var(--color-surface-muted)' }}>
      <Header onOpenTutorial={() => setIsTutorialOpen(true)} />

      <main className="container" style={{ padding: '1.5rem 1rem' }}>
        {/* Printable Header for Homework Submissions */}
        <div className="print-only" style={{ display: 'none', marginBottom: '1.5rem', borderBottom: '2px solid #000', paddingBottom: '0.75rem' }}>
          <h1 style={{ fontSize: '1.8rem', color: '#000', margin: 0 }}>Bode Plot Analysis Report</h1>
          <p style={{ fontSize: '0.9rem', color: '#444', margin: '0.25rem 0 0 0' }}>
            Generated by BudiNgeplot Engineering Studio — Date: {new Date().toLocaleDateString()}
          </p>
        </div>

        {/* Transfer Function Controls Panel */}
        <ControlPanel
          numStr={numStr}
          denStr={denStr}
          exprStr={exprStr}
          zpkGainStr={zpkGainStr}
          zpkZerosStr={zpkZerosStr}
          zpkPolesStr={zpkPolesStr}
          inputMode={inputMode}
          exprError={exprError}
          onNumChange={setNumStr}
          onDenChange={setDenStr}
          onExprChange={setExprStr}
          onZpkGainChange={setZpkGainStr}
          onZpkZerosChange={setZpkZerosStr}
          onZpkPolesChange={setZpkPolesStr}
          onInputModeChange={setInputMode}
          omegaMinPower={omegaMinPower}
          omegaMaxPower={omegaMaxPower}
          onOmegaMinChange={setOmegaMinPower}
          onOmegaMaxChange={setOmegaMaxPower}
          showAsymptotic={showAsymptotic}
          showFactorBreakdown={showFactorBreakdown}
          showMargins={showMargins}
          showGrid={showGrid}
          showPoleZeroMap={showPoleZeroMap}
          onToggleAsymptotic={() => setShowAsymptotic(!showAsymptotic)}
          onToggleFactorBreakdown={() => setShowFactorBreakdown(!showFactorBreakdown)}
          onToggleMargins={() => setShowMargins(!showMargins)}
          onToggleGrid={() => setShowGrid(!showGrid)}
          onTogglePoleZeroMap={() => setShowPoleZeroMap(!showPoleZeroMap)}
        />

        {/* Main Grid: Bode Chart & S-Plane Map */}
        <div className={`main-chart-grid ${showPoleZeroMap ? 'with-map' : 'no-map'}`}>
          <BodeChart
            analysis={analysisResult}
            omegaMinPower={omegaMinPower}
            omegaMaxPower={omegaMaxPower}
            showAsymptotic={showAsymptotic}
            showFactorBreakdown={showFactorBreakdown}
            activeHoverFactorId={activeFactorId}
            selectedFactorId={selectedFactorId}
            onHoverFactor={setHoveredFactorId}
            onSelectFactor={handleSelectFactor}
            showMargins={showMargins}
            showGrid={showGrid}
          />

          {showPoleZeroMap && (
            <PoleZeroMap
              poles={analysisResult.poles}
              zeros={analysisResult.zeros}
            />
          )}
        </div>

        {/* Step-by-step Solution Breakdown for Homework */}
        <HomeworkBreakdown
          analysis={analysisResult}
          activeHoverFactorId={activeFactorId}
          selectedFactorId={selectedFactorId}
          onHoverFactor={setHoveredFactorId}
          onSelectFactor={handleSelectFactor}
        />
      </main>

      {/* Interactive Sadiku Bode Plot Tutorial Modal */}
      <TutorialModal
        isOpen={isTutorialOpen}
        onClose={() => setIsTutorialOpen(false)}
      />
    </div>
  );
};

export default App;
