import React, { useState, useMemo } from 'react';
import { Header } from './components/Header';
import { ControlPanel } from './components/ControlPanel';
import { BodeChart } from './components/BodeChart';
import { PoleZeroMap } from './components/PoleZeroMap';
import { HomeworkBreakdown } from './components/HomeworkBreakdown';
import { analyzeTransferFunction, BodeAnalysisResult } from './utils/bodeEngine';
import { parseTFString } from './utils/stringParser';
import { parseZPK, zpkToPolynomials } from './utils/zpkParser';
import { parseLocalNumberList } from './utils/formatUtils';

export const App: React.FC = () => {
  const [inputMode, setInputMode] = useState<'poly' | 'expr' | 'zpk'>('poly');
  const [numStr, setNumStr] = useState<string>('25');
  const [denStr, setDenStr] = useState<string>('1 4 25');
  const [exprStr, setExprStr] = useState<string>('25 / (s^2 + 4*s + 25)');
  const [zpkGainStr, setZpkGainStr] = useState<string>('25');
  const [zpkZerosStr, setZpkZerosStr] = useState<string>('');
  const [zpkPolesStr, setZpkPolesStr] = useState<string>('-2+4.58j, -2-4.58j');

  const [exprError, setExprError] = useState<string | null>(null);
  const [lastValidCoeffs, setLastValidCoeffs] = useState<{ num: number[]; den: number[] }>({
    num: [25],
    den: [1, 4, 25]
  });

  const [omegaMinPower, setOmegaMinPower] = useState<number>(-2);
  const [omegaMaxPower, setOmegaMaxPower] = useState<number>(4);

  const [showAsymptotic, setShowAsymptotic] = useState<boolean>(true);
  const [showMargins, setShowMargins] = useState<boolean>(true);
  const [showGrid, setShowGrid] = useState<boolean>(true);
  const [showPoleZeroMap, setShowPoleZeroMap] = useState<boolean>(true);

  const [reportMode, setReportMode] = useState<boolean>(false);

  // Compute Bode Analysis Result reactively
  const analysisResult = useMemo<BodeAnalysisResult>(() => {
    let numCoeffs = lastValidCoeffs.num;
    let denCoeffs = lastValidCoeffs.den;

    if (inputMode === 'poly') {
      const parsedNum = parseLocalNumberList(numStr);
      const parsedDen = parseLocalNumberList(denStr);

      if (parsedNum.length > 0 && parsedDen.length > 0) {
        numCoeffs = parsedNum;
        denCoeffs = parsedDen;
        setExprError(null);
        if (JSON.stringify(lastValidCoeffs) !== JSON.stringify({ num: parsedNum, den: parsedDen })) {
          setLastValidCoeffs({ num: parsedNum, den: parsedDen });
        }
      }
    } else if (inputMode === 'expr') {
      const parsed = parseTFString(exprStr);
      if (parsed.error || parsed.numCoeffs.length === 0 || parsed.denCoeffs.length === 0) {
        setExprError(parsed.error || "Incomplete expression syntax");
      } else {
        setExprError(null);
        numCoeffs = parsed.numCoeffs;
        denCoeffs = parsed.denCoeffs;
        if (JSON.stringify(lastValidCoeffs) !== JSON.stringify({ num: parsed.numCoeffs, den: parsed.denCoeffs })) {
          setLastValidCoeffs({ num: parsed.numCoeffs, den: parsed.denCoeffs });
        }
      }
    } else if (inputMode === 'zpk') {
      const parsedZpk = parseZPK(zpkGainStr, zpkZerosStr, zpkPolesStr);
      const polys = zpkToPolynomials(parsedZpk.gain, parsedZpk.zeros, parsedZpk.poles);
      if (polys.numCoeffs.length > 0 && polys.denCoeffs.length > 0) {
        numCoeffs = polys.numCoeffs;
        denCoeffs = polys.denCoeffs;
        setExprError(null);
        if (JSON.stringify(lastValidCoeffs) !== JSON.stringify({ num: polys.numCoeffs, den: polys.denCoeffs })) {
          setLastValidCoeffs({ num: polys.numCoeffs, den: polys.denCoeffs });
        }
      }
    }

    return analyzeTransferFunction(numCoeffs, denCoeffs, omegaMinPower, omegaMaxPower, 400);
  }, [inputMode, numStr, denStr, exprStr, zpkGainStr, zpkZerosStr, zpkPolesStr, omegaMinPower, omegaMaxPower]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div style={{ minHeight: '100dvh', backgroundColor: 'var(--color-surface-muted)' }}>
      <Header
        reportMode={reportMode}
        onToggleReportMode={() => setReportMode(!reportMode)}
        onPrint={handlePrint}
      />

      <main className="container" style={{ padding: '1.5rem 1rem' }}>
        {/* Printable Header for Homework Submissions */}
        <div className="print-only" style={{ display: 'none', marginBottom: '1.5rem', borderBottom: '2px solid #000', paddingBottom: '0.75rem' }}>
          <h1 style={{ fontSize: '1.8rem', color: '#000', margin: 0 }}>Bode Plot Homework Analysis Report</h1>
          <p style={{ fontSize: '0.9rem', color: '#444', margin: '0.25rem 0 0 0' }}>
            Generated by BudiNgeplot Engineering Studio — Date: {new Date().toLocaleDateString()}
          </p>
        </div>

        {/* Controls (Hidden during print) */}
        {!reportMode && (
          <ControlPanel
            numStr={numStr}
            denStr={denStr}
            exprStr={exprStr}
            zpkGainStr={zpkGainStr}
            zpkZerosStr={zpkZerosStr}
            zpkPolesStr={zpkPolesStr}
            inputMode={inputMode}
            exprError={exprError}
            onNumChange={setNumStr}
            onDenChange={setDenStr}
            onExprChange={setExprStr}
            onZpkGainChange={setZpkGainStr}
            onZpkZerosChange={setZpkZerosStr}
            onZpkPolesChange={setZpkPolesStr}
            onInputModeChange={setInputMode}
            omegaMinPower={omegaMinPower}
            omegaMaxPower={omegaMaxPower}
            onOmegaMinChange={setOmegaMinPower}
            onOmegaMaxChange={setOmegaMaxPower}
            showAsymptotic={showAsymptotic}
            showMargins={showMargins}
            showGrid={showGrid}
            showPoleZeroMap={showPoleZeroMap}
            onToggleAsymptotic={() => setShowAsymptotic(!showAsymptotic)}
            onToggleMargins={() => setShowMargins(!showMargins)}
            onToggleGrid={() => setShowGrid(!showGrid)}
            onTogglePoleZeroMap={() => setShowPoleZeroMap(!showPoleZeroMap)}
          />
        )}

        {/* Main Grid Visualizations */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: showPoleZeroMap ? '1fr 340px' : '1fr',
          gap: '1.25rem',
          marginTop: reportMode ? '0' : '1.25rem'
        }}>
          <div>
            <BodeChart
              analysis={analysisResult}
              showAsymptotic={showAsymptotic}
              showMargins={showMargins}
              showGrid={showGrid}
              omegaMinPower={omegaMinPower}
              omegaMaxPower={omegaMaxPower}
            />
          </div>

          {showPoleZeroMap && (
            <div>
              <PoleZeroMap poles={analysisResult.poles} zeros={analysisResult.zeros} />
            </div>
          )}
        </div>

        {/* Step-by-Step Breakdown */}
        <HomeworkBreakdown analysis={analysisResult} />
      </main>
    </div>
  );
};
export default App;
